name: 自动编译 iSH ARM64
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: brew install ninja lld llvm meson
      - run: meson setup build-arm64 -Dguest_arch=arm64 --buildtype=release
      - run: ninja -C build-arm64 ish
      - uses: actions/upload-artifact@v4
        with:
          name: iSH-ARM64-编译完成
          path: build-arm64/ish
